apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rhdh-realm
  namespace: demo-project
spec:
  keycloakCRName: demo-keycloak-instance
  realm:
    id: rhdh
    realm: rhdh
    displayName: "RHDH Realm"
    enabled: true
    browserFlow: browser
    firstBrokerLoginFlow: first broker login
    identityProviders:
      - alias: github
        displayName: "GitHub"
        providerId: github
        enabled: true
        trustEmail: true
        storeToken: false
        addReadTokenRoleOnCreate: false
        authenticateByDefault: false
        linkOnly: false
        firstBrokerLoginFlowAlias: first broker login
        config:
          clientId: "Ov23li8pA4hii34meCr5"
          clientSecret: "3b11837a8eff58114e88953c1d847341ee00611a"
          defaultScope: "user:email"
