apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: rhdh-operator
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAhop+J
