apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: rhdh-operator
data:
  app-config.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://rhdh.apps.cluster-klj6r.dynamic.redhatworkshops.io

    backend:
      auth:
        keys:
          - secret: "${BACKEND_SECRET}"
      baseUrl: https://rhdh.apps.cluster-klj6r.dynamic.redhatworkshops.io
      cors:
        origin: https://rhdh.apps.cluster-klj6r.dynamic.redhatworkshops.io

    auth:
      environment: production
      session:
        secret: "${BACKEND_SECRET}"
      providers:
        oidc:
          production:
            metadataUrl: "https://keycloak-rhdh-operator.apps.cluster-klj6r.dynamic.redhatworkshops.io/realms/rhdh"
            clientId: developer-hub
            clientSecret:
              $env: OIDC_CLIENT_SECRET
            callbackUrl: https://rhdh.apps.cluster-klj6r.dynamic.redhatworkshops.io/api/auth/oidc/handler/frame
            prompt: login  # ⬅ forces redirect to Keycloak (which will show GitHub if configured)
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail
                  dangerouslyAllowSignInWithoutUserInCatalog: true
      dangerouslyAllowSignInWithoutUserInCatalog: true

    signInPage: oidc

    catalog:
      providers:
        keycloakOrg:
          default:
            baseUrl: "https://keycloak-rhdh-operator.apps.cluster-klj6r.dynamic.redhatworkshops.io"
            loginRealm: "rhdh"
            realm: "rhdh"
            clientId: developer-hub
            clientSecret:
              $env: OIDC_CLIENT_SECRET
            schedule:
              frequency: { minutes: 1 }
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail
                  dangerouslyAllowSignInWithoutUserInCatalog: true
